version: "3.9"

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : postgres
      POSTGRES_DB : scrapped_data_database
    ports:
      - 5432:5432
    volumes:
      - pg-data-volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080

volumes:
  pg-data-volume:
    driver: local





